apiVersion: v1
kind: List
items:

- kind: DeploymentConfig
  apiVersion: 'v1'
  metadata:
    labels:
      app: aws-iot
    name: aws-iot
  spec:
    replicas: 1
    selector:
      app: aws-iot
      deploymentconfig: aws-iot
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: aws-iot
          deploymentconfig: aws-iot
      spec:
        containers:
          - env:
            
            #- name: MQTT_MESSAGING_URL
            #  value: "mqtt.enmasse-infra.svc"
            
            volumeMounts:
            # /usr/bin/run will move below files to one central location
            - name: cert-volume-rootca
              mountPath: /opt/app-root/certs1
            - name: cert-volume-cert
              mountPath: /opt/app-root/certs2
            - name: cert-volume-key
              mountPath: /opt/app-root/certs3

            image: ubi8-aws-iot:latest
            imagePullPolicy: Always
            name: aws-iot
            resources: {}
        
        volumes:
          # /usr/bin/run will move below files to one central location
          - name: cert-volume-rootca
            configMap:
              name: root-ca
              items:
              - key: root-CA.crt
                path: root-CA.crt
          
          - name: cert-volume-cert
            configMap:  
              name: cloudpi-cert
              items:
              - key: cloudpi00.cert.pem
                path: cloudpi.cert.pem
          
          - name: cert-volume-key
            configMap:  
              name: cloudpi-key
              items:
              - key: cloudpi00.private.key
                path: cloudpi.private.key

    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - aws-iot
        from:
          kind: ImageStreamTag
          name: ubi8-aws-iot:latest
      type: ImageChange

- kind: BuildConfig
  apiVersion: 'v1'
  metadata:
    name: 'aws-iot'
    annotations:
      description: Base image for everything
      tags: "python,amqp,mqtt"
    labels:
      app: aws-iot
  spec:
    runPolicy: 'Serial' 
    triggers: 
      - type: 'ImageChange'
      - type: 'ConfigChange'
    source: 
      git:
        uri: 'https://github.com/mickuehl/cloudpi.git'
        ref: 'master'
      contextDir: 'examples/aws-iot-example'
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: 'ubi8-aws-iot:latest'
        #namespace: openshift

- kind: ImageStream
  apiVersion: 'v1'
  metadata:
    name: 'ubi8-aws-iot'
    annotations:
      description: Base image for everything
      tags: "python,amqp,mqtt,aws,iot"
    labels:
      app: aws-iot
    #namespace: openshift