apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: cloudpi.cloudpi1
spec:
  username: cloudpi1
  authentication:
    type: password
    password: Fzc3dvcmQK # Base64 encoded
  authorization:
    - addresses: ["sensors"]
      operations: ["send", "recv"]
