
- name: Update the Raspis
  hosts: raspis
  gather_facts: false
  vars_files:
  - vars.yaml

  tasks:
    - name: Update the OS
      remote_user: pi
      become: true
      shell: "apt-get update -y && apt-get upgrade -y"

    - name: Install basic packages
      remote_user: pi
      become: true
      apt:
        pkg:
        - build-essential
        - avahi-utils
        - libopenjp2-7-dev
        - libffi-dev
        - libffi-dev
        - libssl-dev
        - libtiff5-dev
        - gfortran
        - libatlas-base-dev
        - libopenblas-dev
        - libhdf5-serial-dev
        - cdbs
        - git 
        - ntp 
        - sshpass

    - name: Install python
      remote_user: pi
      become: true
      apt:
        pkg:
        - python3 
        - python3-dev 
        - python3-pip 
        - python3-virtualenv 
        - python3-numpy 
        - python3-pandas

    - name: Setup the virtenv
      remote_user: pi
      become: true
      shell: >
        python3 -m virtualenv -p python3 venv --system-site-packages

        echo "# activate the virtenv"  >> ~/.bashrc

        echo "source venv/bin/activate" >> ~/.bashrc
      
    - name: Install Raspberry Pi hardware libs
      remote_user: pi
      become: true
      apt:
        pkg:
        - i2c-tools
        - python3-picamera 
        - python3-rpi.gpio