apiVersion: v1
kind: List
items:

- kind: BuildConfig
  apiVersion: 'v1'
  metadata:
    name: 'hivemq'
    annotations:
      description: HiveMQ base image for everything
      tags: hivemq
    labels:
      runtime: java
  spec:
    
    runPolicy: 'Serial' 
    
    triggers: 
      - type: 'ImageChange'
    
    source: 
      git:
        uri: 'https://github.com/mickuehl/cloudpi.git'
        ref: 'master'
      contextDir: 'deployments/hivemq-ce'
    
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
        
    output:
      to:
        kind: ImageStreamTag
        name: 'hivemq:2019.1'
        #namespace: openshift

- kind: ImageStream
  apiVersion: 'v1'
  metadata:
    name: 'hivemq'
    annotations:
      description: HiveMQ base image for everything
      tags: hivemq
    labels:
      runtime: java
    #namespace: openshift