---
site_name: CloudPi
theme: readthedocs

repo_url: https://github.com/mickuehl/cloudpi/
edit_uri: edit/master/docs
#extra_css:
#  - extra.css

pages:
  - Home: index.md
  - User Guide:
      #- 'Build a car.': guide/build_hardware.md
      - 'Infrastructure setup': guide/setup_infrastructure.md
      - 'Raspberry Pi setup': guide/setup_raspberry.md
      #- 'Create Donkeycar App.': guide/create_application.md
      #- 'Calibrate steering and throttle.': guide/calibrate.md
      #- 'Get driving.': guide/get_driving.md
      #- 'Train an autopilot.': guide/train_autopilot.md
      #- 'Donkey Simulator.': guide/simulator.md
  - Parts:
      - 'About': parts/about.md
      #- 'Actuators': parts/actuators.md
      #- 'Controllers': parts/controllers.md
      #- 'Keras': parts/keras.md
      #- 'Stores': parts/stores.md
      #- 'IMU': parts/imu.md
  #- Utilities:
  #    - 'donkey': utility/donkey.md

  #- Supported Cars: supported_cars.md
  #- Roll Your Own: roll_your_own.md
  #- Contribute: contribute.md
  #- Tests: tests.md
  #- Releases: release.md
  - FAQ: faq.md
  - References: references.md
  #- Legacy: legacy.md