apiVersion: v1
kind: List
items:

- kind: BuildConfig
  apiVersion: 'v1'
  metadata:
    name: 'iot-listener'
    annotations:
      description: Base image for everything
      tags: "python,amqp,mqtt"
    labels:
      app: iot-listener
  spec:
    runPolicy: 'Serial' 
    triggers: 
      - type: 'ImageChange'
      - type: 'ConfigChange'
    source: 
      git:
        uri: 'https://github.com/mickuehl/cloudpi.git'
        ref: 'master'
      contextDir: 'examples/iot-listener'
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: 'ubi8-iot-listener:latest'
        #namespace: openshift

- kind: ImageStream
  apiVersion: 'v1'
  metadata:
    name: 'ubi8-iot-listener'
    annotations:
      description: Base image for everything
      tags: "python,amqp,mqtt,aws,iot"
    labels:
      app: iot-listener
    #namespace: openshift