apiVersion: v1
kind: Template
metadata:
  name: producer
objects:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: producer-${NAME}
    spec:
      containers:
        - name: sender
          image: lulf/enmasse-demo:latest
          imagePullPolicy: Never
          command:
            - /bin/bash
          args:
            - -c
            - /send.py -a ${MESSAGING_URL} -r ${RATE}
parameters:
  - name: MESSAGING_URL
    value: amqps://test:test@messaging.enmasse-space1.svc:5671/myaddress
    description: AMQP url to destination
    required: true
  - name: RATE
    value: "0.5"
    description: Producer send rate (per second)
    required: true
  - name: NAME
    description: Name of pod
    required: true
